media:
  name: uploads
  label: Uploads
  input: uploads
  output: /uploads/
  categories:
    - image
    - audio
    - video
    - document
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: "{year}-{month}-{day}-{primary}.md"
    format: yaml-frontmatter
    fields:
      - name: layout
        type: string
        hidden: true
        default: "post"
      - name: title
        label: Title
        type: string
      - name: body
        label: Content
        type: rich-text
      - name: date
        label: Date
        type: date
        required: true
        options:
          time: true
          format: dd-MM-yyyy HH:mm
      - name: image
        label: Cover Image
        type: image
        options:
          media: uploads
          categories:
            - image
      - name: tags
        label: Tags
        type: string
        list: true
      - name: published
        label: Published
        type: boolean
        default: false
    view:
      fields:
        - title
        - date
        - published
      sort:
        - date
        - title
      layout: list
      primary: title
