media:
  - name: files
    label: Files
    input: uploads/files
    output: /uploads/files
    categories:
      - document
      - compressed
  - name: media
    label: Media
    input: uploads/media
    output: /uploads/media
    categories:
      - image
      - video
      - audio
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename: '{year}/{year}-{month}-{day}-{primary}.md'
    fields:
      - name: layout
        label: Layout
        type: string
        value: post
        hidden: true
      - name: title
        label: Title
        type: string
        default: ""
        required: true
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ssxxx
      - name: body
        label: Body
        type: rich-text
      - name: category
        label: Category
        type: select
        required: true
        options:
          values:
            - Notas
            - Links
            - Fotos
            - Esquinas
          multiple: false
          creatable: false
      - name: tags
        label: Tags
        type: select
        required: true
        options:
          values:
            - filmes
            - músicas
            - séries
            - leituras
            - jogos
          multiple: true
          creatable: true
      - name: syndicate_to
        label: Syndication
        type: select
        options:
          values:
            - label: Bluesky
              value: bluesky
            - label: Mastodon
              value: mastodon
            - label: Flickr
              value: flickr
          multiple: true
          creatable: false
      - name: published
        label: Published
        type: boolean
      - name: slug
        label: Permalink
        type: string
        required: true
      - name: source
        label: Source Link
        type: string
    view:
      fields:
        - date
        - title
        - slug
        - category
      sort:
        - date
        - title
        - published
      primary: slug
      search:
        - title
        - slug
        - category
        - tags
        - body
      layout: tree
    subfolders: true