media: uploads

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields:
        - date
        - title
      sort:
        - date
      search:
        - title
        - body
        - tags
    fields:
      - name: layout
        type: string
        hidden: true
        default: post
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text 
      - name: tags
        label: Tags
        list: true
        type: string
      - name: date
        label: Date
        type: date
        options:
          time: true
          format: yyyy-MM-dd' 'HH:mm:ss' 'xxxx
      - name: now
        label: Status post
        type: boolean
      - name: published
        label: Published
        type: boolean
        default: false
