# Site Settings

title: Arthur Freitas
email: arthur@arthr.me
description: >-
  Faço sites e outras coisas na internet.
baseurl: ""
url: "https://arthr.me"

lang: pt-BR
timezone: America/Sao_Paulo
logo: /assets/avatar.png

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - lib
  - script
  - test
  - docs
  - README.md
  - Gemfile
  - Gemfile.lock


seo:
  name: Arthur Freitas
  links:
    - https://irrelefante.com.br/
    - https://bsky.app/profile/arthr.me
    - https://tangled.org/arthr.me/
    - https://grain.social/profile/arthr.me
    - https://www.last.fm/user/arthrfrts
    - https://letterboxd.com/arthrfrts
    - https://organica.social/@arthr
