# Site settings
title: Arthur Freitas
description: >-
  Eu faço sites adoráveis e artesanais para pessoas bacanas ao redor do mundo.

baseurl: ""
url: "https://arthr.me"

lang: pt-BR
timezone: America/Sao_Paulo
encoding: utf-8

logo: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128

author:
  name: Arthur Freitas
  url: https://arthr.me
  email: email@arthr.me
  picture: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128

# Menu
main_menu:
  title: Navegar
  items:
    - url: /
      label: Agora
    - url: /sobre/
      label: Sobre

footer_menu:
  title: Acompanhe esse blog
  items:
    - url: /feed.xml
      label: Feed
    - url: /feed.json
      label: JSON Feed
    - url: https://bsky.app/profile/arthr.me
      label: Bluesky

# Build settings
include:
  - _redirects

permalink: /:year/:month/:title:output_ext

theme: minduim

plugins:
  - jekyll-relative-links

seo:
  name: Arthur Freitas
  links:
    - https://github.com/arthrfrts
    - https://linkedin.com/in/arthrfrts
    - https://bsky.app/profile/arthr.me
    - https://www.tumblr.com/arthrfrts
    - https://www.last.fm/user/arthrfrts
    - https://letterboxd.com/arthrfrts

relative_links:
  enabled: true
  collections: true

# Theme
minduim:
  date_formats:
    day: "%d/%m/%Y"
    month: "%m/%Y"
    year: "%Y"
  translations:
    jump_to_navigation: "Pular para a navegação"
    jump_to_content: "Pular para o conteúdo"
    archive_date_title: "Posts em %s"
    archive_tag_title: "Posts sobre “%s”"
    archive_category_title: "Arquivo de %s"
    post_tagged_with: "Tags:"
    blog_pagination_title: "Paginação do blog"
    blog_pagination_next_page: "Posts anteriores &rarr;"
    blog_pagination_prev_page: "&larr; Posts mais recentes"
