# Site settings
title: Arthur Freitas
description: >-
  Eu faço experiências adoráveis e artesanais na web para pessoas bacanas ao redor do mundo.

baseurl: ""
url: "https://arthr.me"
logo: /assets/img/avatar.png

lang: pt-BR
timezone: America/Sao_Paulo
encoding: utf-8

author:
  name: Arthur Freitas
  url: https://arthr.me
  email: email@arthr.me
  picture: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128


main_menu:
  - label: Sobre mim
    url: /sobre
  - label: Dê um oi
    url: email@arthr.me

# Build settings
permalink: /blog/:year/:month/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled:
    - year
    - month
    - tags
  layout: archive
  permalinks:
    year: "/blog/:year/"
    month: "/blog/:year/:month/"
    tag: "/blog/tags/:name/"
  slug_mode: latin

seo:
  name: Arthur Freitas
  links:
    - https://github.com/arthrfrts
    - https://linkedin.com/in/arthrfrts
    - https://letterboxd.com/arthrfrts
    - https://www.tumblr.com/arthrfrts
