# Site settings
title: arthr.me
description: >-
  Nada faz muito sentido.

baseurl: ""
url: "https://arthr.me"

lang: pt-BR
timezone: America/Sao_Paulo
encoding: utf-8

logo: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128

author:
  name: Arthur Freitas
  url: https://arthr.me
  email: email@arthr.me
  picture: https://gravatar.com/avatar/63d8285c2a55e1d4fefe7747e2c17ead9d3654dc39c4791adf088484105e5000?size=128

# Menu
main_menu:
  title: Navegar
  items:
    - url: /
      label: Agora
    - url: /sobre.html
      label: Sobre

# Build settings
include:
  - _redirects

permalink: /blog/:year/:month/:title:output_ext

remote_theme: arthrfrts/minduim@latest

plugins:
  - jekyll-remote-theme
  - jekyll-relative-links

seo:
  name: Arthur Freitas
  links:
    - https://github.com/arthrfrts
    - https://linkedin.com/in/arthrfrts
    - https://bsky.app/profile/arthr.me
    - https://www.tumblr.com/arthrfrts
    - https://www.last.fm/user/arthrfrts
    - https://letterboxd.com/arthrfrts

relative_links:
  enabled: true
  collections: true
