# Site Settings

title: Arthur Freitas
email: arthur@arthr.me
description: >-
  Faço sites e outras coisas na internet.
baseurl: ""
url: "https://arthr.me"

lang: pt-BR
timezone: America/Sao_Paulo
logo: /assets/avatar.png

menu:
  - label: 🙋‍♂️ Sobre mim
    url: /sobre/
  - label: 📫 Dê um oi
    url: mailto:arthur@arthr.me
  - label: 📚 Portfólio
    url: https://arthr.dev/
    rel: me
  - label: 📓 Blog
    url: https://irrelefante.com.br/
    rel: me
  - label: 💭 Microblog
    url: https://bsky.app/profile/arthr.me
    rel: me atproto
  - label: 📷 Fotolog
    url: https://grain.social/profile/arthr.me
    rel: me
  - label: 👨‍💻 Códigos
    url: https://tangled.org/arthr.me
    rel: me

# Build settings
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - lib
  - script
  - test
  - docs
  - README.md
  - Gemfile
  - Gemfile.lock

seo:
  name: Arthur Freitas
  links:
    - https://irrelefante.com.br/
    - https://bsky.app/profile/arthr.me
    - https://tangled.org/arthr.me/
    - https://grain.social/profile/arthr.me
    - https://github.com/arthrfrts
    - https://letterboxd.com/arthrfrts
    - https://organica.social/@arthr
