name: Issue to Jekyll Post

on:
  issues:
    types: [opened]

jobs:
  create-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    
    steps:
      - uses: actions/checkout@v4

      - name: Process Issue to Post
        id: process
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            const fs = require('fs');
            const issue = context.payload.issue;
            const title = issue.title;
            const body = issue.body;
            
            let tags = [];
            const tagsMatch = body.match(/Tags:(.+)$/im);
            if (tagsMatch) {
              tags = tagsMatch[1].split(',').map(tag => tag.trim());
            }
            
            let content = body.replace(/Tags:(.+)$/im, '').trim();
            
            const imageRegex = /!\[([^\]]*)\]\(data:image\/[^;]+;base64,([^)]+)\)/g;
            const images = [];
            let match;
            
            while ((match = imageRegex.exec(content)) !== null) {
              const alt = match[1];
              const base64 = match[2];
              const filename = `${Date.now()}-${images.length}.png`;
              
              const buffer = Buffer.from(base64, 'base64');
              fs.mkdirSync('uploads', { recursive: true });
              fs.writeFileSync(`uploads/${filename}`, buffer);
              
              content = content.replace(match[0], `![${alt}](/uploads/${filename})`);
              images.push(filename);
            }
            
            const date = new Date();
            const slug = title
              .toLowerCase()
              .replace(/[^\w\s-]/g, '')
              .replace(/\s+/g, '-');
            const filename = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}-${slug}.md`;
            
            const frontMatter = [
              '---',
              `title: "${title}"`,
              `date: ${date.toISOString()}`,
              'layout: post',
              'tags:',
              ...tags.map(tag => `  - ${tag}`),
              '---',
              '',
              content
            ].join('\n');
            
            const path = `_posts/${filename}`;
            fs.writeFileSync(path, frontMatter);
            
            execSync('git config --global user.email "github-actions[bot]@users.noreply.github.com"');
            execSync('git config --global user.name "github-actions[bot]"');
            execSync('git add .');
            execSync(`git commit -m "Add post: ${title}"`);
            execSync('git push');
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: `Post criado em \`${path}\``
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed'
            });
