name: Build & deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - uses: actions/cache@v4
        with:
          path: .jekyll-cache
          key: jekyll-cache-${{ github.run_id }}
          restore-keys: jekyll-cache-

      - run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy _site --project-name=SEU_PROJETO
